### ISSUE TITLE
Buggy Table Widths on Shortlist Items

### ISSUE THREAD

**Issue by bradhgq** [kvnxiao/waterlooworksplus#1]
When formatting job postings in the shortlist, the table widths are not properly formatted. When click on header to sort, the width formatting would be good again. Device is Acer Spin 5 on Windows 10, using WaterlooWorks Plus alongside WaterlooWorks Now Extension.

![image](https://user-images.githubusercontent.com/21327628/45931420-05242d00-bf3c-11e8-8abe-6ea9cb525a5f.png)

**Comment by kvnxiao** [comment]
What desktop resolution is your device, and what viewport resolution is your device (check from https://www.mydevice.io/)?

I need to revamp the extension anyways, since there seems to be a "double-tab opening" issue now. Probably has to do with them updating the website again, albeit still poorly.

**Comment by bradhgq** [comment]
My desktop resolution is 1920x1080, and my viewport resolution is 1280x720 as I have a 1.5x magnifier (thanks windows). Also, I tried disabling the WaterlooWorks Now extension and the problem went away - since they mentioned that WaterlooWorks Now might not be compatible with other extensions (see below), I will email them next.

Thanks!

![image](https://user-images.githubusercontent.com/21327628/45934930-1b99ab00-bf73-11e8-9f57-bd28d00f0295.png)

**Comment by kvnxiao** [comment]
Thanks for the note, sounds good to me.
